### ISSUE TITLE
Suggested edit for YubiHSM2/Concepts/Algorithms

### ISSUE THREAD

**Issue by Jiang-BW** [Yubico/developers.yubico.com#107]
Could you please list all the values of these algorithms for the yubihsm-shell and C coding? For example, if I want to set the algorithm using yubihsm-shell or set in C code, what should I set?

**Comment by klali** [comment]
I've updated this on https://developers.yubico.com/YubiHSM2/Concepts/Algorithms.html is it clearer now? If not, what more would you like to see on that page?

**Comment by Jiang-BW** [comment]
Great! Thank you!

Jiang

Sent from my iPhone

On Feb 23, 2018, at 12:27 AM, Klas Lindfors <notifications@github.com<mailto:notifications@github.com>> wrote:


I've updated this on https://developers.yubico.com/YubiHSM2/Concepts/Algorithms.html is it clearer now? If not, what more would you like to see on that page?

**Comment by Jiang-BW** [comment]
Hi, there,

I have made a request for https://github.com/Yubico/developers.yubico.com/issues/109 <https://github.com/Yubico/developers.yubico.com/issues/109>. Can anybody tell if this doable?


Best Regards,

Jiang

**Comment by Jiang-BW** [comment]
Or is there some other way to do it?


Best Regards,

Jiang
