### ISSUE TITLE
Does it support ECC signatures?

### ISSUE THREAD

**Issue by miguelUS** [Yubico/developers.yubico.com#111]
In the first paragraph it says: "it enables RSA or ECC sign/encrypt operations using a private key stored on a smartcard (such as the YubiKey NEO)"
Then the NOTE below says "The YubiKey does not support ECC PGP operations"
I think this needs clarification.

**Comment by a-dma** [comment]
Which part needs clarification? OpenPGP card is a standard that supports RSA and ECC whereas YubiKeys only implement RSA.

**Comment by miguelUS** [comment]
I guess if it explicitly said that the YubiKey doesn't implement the full
set of algorithms in the standard, rather than having that part in a note.
My point is that if readers get the idea that the YubiKey implements
OpenPGP that's the part that sticks in their minds. But that's my opinion,
likely others may not agree. In any case, thanks for reviewing.

On Mar 2, 2018 3:59 AM, "Alessio Di Mauro" <notifications@github.com> wrote:

Which part needs clarification? OpenPGP card is a standard that supports
RSA and ECC whereas YubiKeys only implement RSA.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Yubico/developers.yubico.com/issues/111#issuecomment-369903026>,
or mute the thread

**Comment by a-dma** [comment]
Would replacing the part in the note with `The YubiKey only supports RSA keys for OpenPGP. ECC keys are not supported` work better?

**Comment by miguelUS** [comment]
Yes, I think that will be better.

On Mar 2, 2018 4:30 AM, "Alessio Di Mauro" <notifications@github.com> wrote:

Would replacing the part in the note with The YubiKey only supports RSA
keys for OpenPGP. ECC keys are not supported work better?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Yubico/developers.yubico.com/issues/111#issuecomment-369908722>,
or mute the thread

**Comment by a-dma** [comment]
Changed. It will be live shortly.

**Comment by zacharydrew** [comment]
It appears this issue needs an update as of Oct 11, 2019: [YubiKey 5.2.3 Enhancements to OpenPGP 3.4 Support](https://support.yubico.com/support/solutions/articles/15000027139-yubikey-5-2-3-enhancements-to-openpgp-3-4-support)
