### ISSUE TITLE
Suggested edit for OTP/OTPs_Explained

### ISSUE THREAD

**Issue by chanchanzhang** [Yubico/developers.yubico.com#119]
How is the passcode generated and verified?

**Comment by nevun** [comment]
This is explained on https://developers.yubico.com/OTP/OTPs_Explained.html:

"The passcode is generated from a multitude of random sources, including counters for both YubiKey sessions and OTPs generated. When a Yubico OTP is verified, the session and OTP counter values are compared to last values submitted. If the counters are less than the previously used values the OTP is rejected"
 
Please re-open and explain in more detail if what you need to know if that is not enough.

Thank you!
