### ISSUE TITLE
Suggested edit for PIV/Guides/SSH_with_PIV_and_PKCS11

### ISSUE THREAD

**Issue by tsuna** [Yubico/developers.yubico.com#168]
The recommendation that "Homebrew users can use `export OPENSC_LIBS=$(brew --prefix opensc)/lib`." is incorrect at least as of MacOS Sierra (10.13.x). It will lead to:
```
$ ssh-add -s $OPENSC_LIBS/opensc-pkcs11.so
Enter passphrase for PKCS#11: 
Could not add card "/usr/local/opt/opensc/lib/opensc-pkcs11.so": agent refused operation
```
Because ssh-agent does not allow `/usr/local/opt/opensc/lib/opensc-pkcs11.so`. Instead the workaround is:
```
sudo ln -f `brew list opensc | grep lib/opensc-pkcs11.so` /usr/local/lib/opensc-pkcs11.so
```

Related issues: Homebrew/homebrew-core#16385 OpenSC/OpenSC#1007 OpenSC/OpenSC#1008 #88 #153

**Comment by dch** [comment]
this would be better expressed as `find -E /usr/local/Cellar/opensc/ -name opensc-pkcs11.so -type f | head -1`
