### ISSUE TITLE
Suggested edit for PGP/Importing_keys

### ISSUE THREAD

**Issue by indolering** [Yubico/developers.yubico.com#17]
This tutorial does not inform the user that they need to set a pin for their Yubikey and the instructions do not include the pin entry step.  When going through it for the first time, I thought that the pin referred to my PGP key password.  It took some googling to figure out.

**Comment by sanmai-NL** [comment]
Is anything being done about this issue? Quite disappointing you let it unresolved and unanswered for more than half a year.

**Comment by dainnilsson** [comment]
This issue (as well as the others) will be dealt with. We have plans to restructure the OpenPGP documents a bit, as well as re-writing some of it, which should clarify this among other things. Unfortunately this has been a bit neglected as other projects have gotten priority over it. I hope to rectify this soon-ish. I'm sorry for the delay.

**Comment by sanmai-NL** [comment]
Thanks for letting this know. It doesn't seem like much work to take up the correction suggestions I see here ...

**Comment by thorduri** [comment]
This has been addressed by a number of recent PRs.

Further work on the documents is ongoing.
