### ISSUE TITLE
YubiHSM2 session failed

### ISSUE THREAD

**Issue by evso9816** [Yubico/developers.yubico.com#200]
Hi,
I just bought a new HSM2, but have trouble to get it identified. Below are some few results I share to request help from anyone who can:

http://127.0.0.1:12345/connector/status
status=**NO_DEVICE**
serial=*
version=2.0.0
pid=3482
address=localhost
port=12345

**yubihsm-connector -d**
DEBU[0000] preflight complete                            cert= config= key= pid=3482 seccomp=false serial= syslog=false version=2.0.0
DEBU[0000] takeoff                                       TLS=false listen="localhost:12345" pid=3482
DEBU[0018] reopening usb context                         Correlation-ID=929e8cf8-0555-3f0b-256e-682a5b412d40 why="status request"
DEBU[0018] usb context not yet open                      Correlation-ID=929e8cf8-0555-3f0b-256e-682a5b412d40
WARN[0018] status failed to open usb device              X-Request-ID=929e8cf8-0555-3f0b-256e-682a5b412d40 error="_libusb: bad access [code -3]_"
INFO[0018] handled request                               Content-Length=0 Content-Type= Method=GET RemoteAddr="127.0.0.1:55602" StatusCode=200 URI=/connector/status User-Agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" X-Real-IP=127.0.0.1 X-Request-ID=929e8cf8-0555-3f0b-256e-682a5b412d40 latency=2.793283ms
DEBU[0073] reopening usb context                         Correlation-ID=f89d1ffc-29be-89d0-fdb4-4b4ce6bdd68c why="status request"
WARN[0073] status failed to open usb device              X-Request-ID=f89d1ffc-29be-89d0-fdb4-4b4ce6bdd68c error="libusb: bad access [code -3]"
INFO[0073] handled request                               Content-Length=0 Content-Type= Method=GET RemoteAddr="127.0.0.1:55604" StatusCode=200 URI=/connector/status User-Agent="YubiHSM curl/2.0.1" X-Real-IP=127.0.0.1 X-Request-ID=f89d1ffc-29be-89d0-fdb4-4b4ce6bdd68c latency="188.349µs"
ERRO[0129] failed usb proxy                              X-Request-ID=9bf5d155-8420-fa27-bfe0-12de245b1cbc error="libusb: bad access [code -3]"
ERRO[0129] error in handling request                     Content-Length=13 Content-Type=application/octet-stream Method=POST RemoteAddr="127.0.0.1:55604" StatusCode=500 URI=/connector/api User-Agent="YubiHSM curl/2.0.1" X-Real-IP=127.0.0.1 X-Request-ID=9bf5d155-8420-fa27-bfe0-12de245b1cbc latency="113.539µs"

yubihsm> session open 1 password
[LIB - INT 14:51:59.349263] yubihsm.c:666 (yh_create_session): Host challenge: d7f02d463e5ac92c
[LIB - NET 14:51:59.349349] yubihsm.c:82 (send_msg):  SEND >> (03 + 0010) 03 000a 0001d7f02d463e5a c92c
[LIB - ERR 14:51:59.349947] yubihsm_curl.c:185 (backend_send_msg): Curl perform failed: 'The requested URL returned error: 500 Internal Server Error'
[LIB - ERR 14:51:59.349976] yubihsm.c:746 (yh_create_session): Connection error
Failed to create session: Connection error

Thanks for your help!

**Comment by a-dma** [comment]
Do you have permissions to open the USB device? You need either a udev rule like the one at https://developers.yubico.com/YubiHSM2/Component_Reference/yubihsm-connector/ or to run the connector as root (or a user with enough privileges).

**Comment by evso9816** [comment]
You're right! running with "sudo" gets things done nicely!
Thanks a-dma!
