### ISSUE TITLE
Suggested edit for PGP/Card_edit to reflect security fixes.

### ISSUE THREAD

**Issue by jonathancross** [Yubico/developers.yubico.com#21]
According to [SecurityAdvisory 2015-04-14](https://developers.yubico.com/ykneo-openpgp/SecurityAdvisory%202015-04-14.html) all versions of this OpenPGP applet `1.0.9` or earlier should be replaced. The page [PGP/Card_edit](https://github.com/Yubico/developers.yubico.com/blob/master/content/PGP/Card_edit.adoc) should be updated as it references older versions of the applet, firmware and required software which probably won't work or will produce different output.
Example:
> Where "01 00 05" means version 1.0.5.

Live version of the page: https://developers.yubico.com/PGP/Card_edit.html

**Comment by dainnilsson** [comment]
Closing this now as the document has recently been updated significantly and should not be outdated.
