### ISSUE TITLE
Suggested edit for PIV/Guides/SSH_with_PIV_and_PKCS11

### ISSUE THREAD

**Issue by jmyreen** [Yubico/developers.yubico.com#240]
### Prerequisites:

For Windows, the Putty-CAC fork of the Putty SSH client can be used. This version of Putty supports smart cards, and can be downloaded from https://github.com/NoMoreFood/putty-cac/releases

The Windows version of OpenSC can be downloaded from https://github.com/OpenSC/OpenSC/wiki

### 4. Find out where OpenSC has installed the pkcs11 module

On Windows, the path is typically `C:\program files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll
`
### 6. Authenticate to the target system using the new key:

Using Putty-CAC on Windows, select Certificate under Connection/SSH. Click the "Select PKCS Cert..." button and browse to file containing the pkcs11 module and click Open. In the window that opens, select the certificate on the Yubikey. These settings can be stored as a Putty named session.

![image](https://user-images.githubusercontent.com/28989107/67795308-b920b180-fa86-11e9-9338-b79e97b2ed70.png)

**Comment by joostd** [comment]
Closing this issue, as we have a YubiKey-specific version of a PKCS#11 module now (YKCS11), so OpenSC is no longer required nor preferred.
