### ISSUE TITLE
Suggested edit for PGP/Importing_keys

### ISSUE THREAD

**Issue by alfonz19** [Yubico/developers.yubico.com#243]
about "gpg-connect-agent --hex "scd apdu 00 f1 00 00" /bye"

* command not explained.
* command does not work
* after reinsterting token it prints: ERR 100663406 Card removed <SCD>
* after another reinsert of token it prints the same until `gpg --card-status` is issued
* only after that command works.

**Comment by kojishoda** [comment]
I would like to request  your support 
 at the first..

**Comment by alfonz19** [comment]
Sorry, I don't understand what do you want from me.

But anyways, it has been more than 2 months, and I completely lost context. Also given the state of documentation of yubico(mostly obsoleted not working chaos, no offense), I to stop exploring yubico capabilites, and resorted to using what I really really needed and manage how to make it working using personal blogs on internet(!) and some linux forums, and just forgot about other capabilities. Also I was explained, that my (free!) help with improving state of documentation of yubico (despite of its state) is not needed, and the team can handle it on its own. ~ Even if you want my help now, I cannot help you any more, because I don't remember the details. But it's rather easy. Open which ever documentation page, forget that you have some yubico knowlegde and try to follow any walkthrough. You will very very soon find yourself lost in inspecific, vague, misleading and mostly obsoleted documentation. There aren't small things to get right, there is huge obsoleted mess to be cleaned by someone, which needs participation from someone on yubico side, and that is non-existent, thus it's not going to be me.

Sorry for not closing this ticket earlier.
