### ISSUE TITLE
Unclear what capabilities are required to generate signing key with YubiHSM2 KSP

### ISSUE THREAD

**Issue by dquist** [Yubico/developers.yubico.com#252]
I've been trying to follow the [Code Signing Example] for YubiHSM using the Windows key storage provider. The CSR .inf file works out of the box with the default HSM authentication key configured, but I was having trouble finding how to generate a CSR with a different authentication key. Specifically, I can't find what capabilities are required to generate a code signing CSR.

My first attempt was to generate an authentication key that had the capability of `generate-asymmetric-key` and the delegated capability of `sign-pkcs`. 

```
put authkey 0 2 authkey 1 generate-asymmetric-key sign-pkcs
```
That seemed logical to me since I only wanted the key be able to generate signing keys, not perform signing itself. However I would always get the `NTE_BAD_KEYSET_PARAM` error as shown below.

![image](https://user-images.githubusercontent.com/3596043/70018433-a7ca3980-154b-11ea-8b0c-61429fc6b9ce.png)

Through a process of trial and error I determined what the minimum capabilities and delegated capabilities are required to generate a CSR which is shown below.

```
put authkey 0 2 authkey 1 generate-asymmetric-key,sign-pkcs sign-pkcs,decrypt-oaep
```

I can generate CSRs using that authentication key, but if I remove any of them the generation will fail. This doesn't make sense to me though. Why does the key that generates the CSR need the s`ign-pkcs` capability? And why is the `decrypt-oaep` delegated capability required?

It would be helpful if someone could shed some light on this so I could be a little more certain that I have the correct capabilities configured.

[Code Signing Example]: https://developers.yubico.com/YubiHSM2/Component_Reference/KSP/Code_Signing_Example.html

**Comment by dquist** [comment]
Well I answered my own question somewhat. I discovered that `decrypt-oaep` can be replaced with `decrypt-pkcs` and the CSR still works which makes a bit more sense.

**Comment by klali** [comment]
No decrypt capabilities should be needed.

the first set of capabilities you put in is what the authkey itself is authorized for, the second is capabilities it's allowed to set on created objects. How are you creating the key associated with the CSR?

The reason the sign-pkcs capability is needed is because the CSR is self-signed and you also need it later to actually use the key to produce signatures.

**Comment by dquist** [comment]
Thanks for the response!

> the first set of capabilities you put in is what the authkey itself is authorized for, the second is capabilities it's allowed to set on created objects. How are you creating the key associated with the CSR?

Yes, I understand the delegated capabilities. To generate the CSR I'm using the Key Storage Provider and certreq.exe on Windows with the .inf file from the linked example. Invoking certreq.exe is generates a new key along with the CSR, which from what I've seen is the only way to go about this. The .inf format has the `UseExistingKeySet` option which has a default value of false. If I try to set it to true I have to either set a value for `RenewalCert` or `KeyContainer` per the [docs](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certreq_1), both of which produce a 'operation not supported' error when using the YubiHSM KSP.

> This parameter is used to specify that an existing key pair should be used in building a certificate request. If this key is set to TRUE, you must also specify a value for the RenewalCert key or the KeyContainer name.

> The reason the sign-pkcs capability is needed is because the CSR is self-signed and you also need it later to actually use the key to produce signatures.

Ok, the self-signing CSR makes sense. I suspected it was something along those lines. As far as actually producing signatures, my plan to was to actually have two separate authentication keys - one for generating the key pairs and one for performing the signatures. Since the generating key needs to have the `sign-pkcs` capability, I think I will just delete the object after the pair is generated and create a new auth key that **only** has the `sign-pkcs` capability. That seems to be working.

> No decrypt capabilities should be needed.

That's also what I expected but doesn't seem to be the case. If I remove the `decrypt-pkcs` capability the CSR generation with certreq will fail. Not a huge issue, I was just trying to understand if there was a reason.  Maybe I will take a look at the audit log today to see what operations are actually being performed, that could shed some light on that.

This whole process has got me wondering though, is there an easy way to generate a CSR without using certreq?? I think ideally my CSR would use a key pair that I've already generated on the device -but that doesn't seem to be possible using the KSP.

Would you accept a PR to add some of this information to the KSP example?

**Comment by klali** [comment]
Ok, I think I understand then, you create the key and the CSR from the certreq utility. The decision to include the decrypt capability on the generated key is based on how certreq calls into the ksp.

For actual usage only the signing capability will be used, but apparently the created key needs a decrypt capability because certreq passes that down. You should be able to create the key and cert in other ways, for maximum flexibility openssl and pkcs11 comes to mind.

Pull requests clarifying things like this are welcome.

**Comment by klali** [comment]
actually, you could try to add in the .inf file, under the [NewRequest] heading:

KeyUsageProperty = NCRYPT_ALLOW_SIGNING_FLAG

**Comment by dquist** [comment]
> KeyUsageProperty = NCRYPT_ALLOW_SIGNING_FLAG

Yes! That worked! Great find, thank you.

> You should be able to create the key and cert in other ways, for maximum flexibility openssl and pkcs11 comes to mind.

Ok, great, I think I just need to familiarize myself with that process then. Are these the docs I should be following for that?
https://developers.yubico.com/YubiHSM2/Usage_Guides/OpenSSL_with_pkcs11_engine.html

**Comment by klali** [comment]
Ok, interesting. I'll amend that doc then (unless you feel like making a pull request?)

Yeah, that doc is probably a good starting point, but if you're getting the certreq+ksp to do the right thing it might be unnecessary.

**Comment by dquist** [comment]
I'll make a PR, there's another typo I need to correct elsewhere anyway.

I have the KSP doing what I want for the most part - the one drawback is that the keys generated by KSP can't be backed up because they lack the `exportable-under-wrap` capability. Not a deal breaker for our use case by any means, but that would be my primary motivation for using openssl to generate a CSR using an existing key pair.

Unless there's a way to add the `exportable-under-wrap` capability through KSP that I'm not aware of. I tried setting `ExportableEncrypted = TRUE` in the inf file but that gave me a `NTE_NOT_SUPPORTED` error.

![image](https://user-images.githubusercontent.com/3596043/70145544-f0761580-1665-11ea-9750-0a24286d8614.png)

**Comment by klali** [comment]
If you add exportable-under-wrap as a delegated capability of the authkey you use with the ksp it should use that for any generated keys.

**Comment by dquist** [comment]
Thank you, adding `exportable-under-wrap` as a delegated capability worked. I'm not sure why I didn't think of that. Now I have everything I need 😎.
