### ISSUE TITLE
Link from SSH+PGP to SSH+PIV pages

### ISSUE THREAD

**Issue by jsha** [Yubico/developers.yubico.com#277]
Right now if you search Google for [yubikey ssh], you'll wind up at the page that describes how to use the OpenPGP applet to do SSH:

https://developers.yubico.com/PGP/SSH_authentication/

However, it's also possible to use PIV, as described at

https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html

I've talked to a lot of people who get the impression that OpenPGP is the "best" or "official" way to do SSH with a Yubikey, but when I show them how to use PIV, they find it much easier. I think it would be really beneficial for the PGP+SSH main page, plus the platform-specific guides, to prominently state near the top that PIV is also available and many people find PIV easier to set up and use.

**Comment by joostd** [comment]
Thank you for the suggestion. We will update our documentation and refer to [Securing SSH with the YubiKey](https://developers.yubico.com/SSH/) to list the different options (which now also includes using FIDO with SSH). See https://github.com/Yubico/developers.yubico.com/pull/595.
