### ISSUE TITLE
Suggested edit for PGP/SSH_authentication

### ISSUE THREAD

**Issue by itinerarium** [Yubico/developers.yubico.com#32]
Yubikey 4 and Fedora 23 work well together. However, there does not appear to be a guide that pairs the Yubikey 4 with the more recent gpg2 options and user-friendly minimal configuration for current environments. While it was helpful to follow the guides linked at https://developers.yubico.com/PGP/SSH_authentication/ to get started, some of the instructions did not appear to be relevant and some of the commands yielded warnings about deprecated options.

After playing around a bit with the Yubikey 4, I wrote a guide https://www.0n0e.com/public/yubikey-4-guide/ that may helpful for users looking to get started with the newest Yubikey on a recent Linux environment. It would be great to have the guide linked on https://developers.yubico.com/PGP/SSH_authentication/ .

With regard to specific issues:

https://www.esev.com/blog/post/2015-01-pgp-ssh-key-on-yubikey-neo/ is outdated in that --expert --gen-key will not offer full options on GnuPG 2.1.9 and as mode switching no longer appears to be necessary.

https://github.com/dainnilsson/scripts/blob/master/base-install/gpg.sh is outdated in that --write-env-file is a deprecated option.

https://jclement.ca/articles/2015/gpg-smartcard/ is outdated in that mode switching no longer appears to be necessary, --write-env-file is a deprecated option, and Gnome keyring's interference does not appear to be present on Fedora 23 (Cinnamon spin).

Thank you in advance for your consideration.

**Comment by thorduri** [comment]
Some of these have been updated (e.g. the `gpg.sh` script by @dainnilsson) since this issue was created.

We are also working on official guides, and we'll not be adding any further links to the page.

Thanks for the report!
