### ISSUE TITLE
Suggested edit for PGP/index

### ISSUE THREAD

**Issue by jonathancross** [Yubico/developers.yubico.com#33]
The navigation of the "PGP" section of the site is confusing and gives users the impression that there is less pages than actually exist.
Ideally, the "OpenPGP App" section[1] should be listed inside the "PGP" section on the left as a sub-item.

[1] https://developers.yubico.com/ykneo-openpgp/

**Comment by thorduri** [comment]
We'll be moving some of the documentation around, putting it under the PGP section -- similar to what was done for the PIV docs.

This will be addressed as a part of that work.
