### ISSUE TITLE
Suggested edit for U2F/Protocol_details/Overview

### ISSUE THREAD

**Issue by gurudeep-singh** [Yubico/developers.yubico.com#35]
Device cloning section assumes that attacker would be able to copy keys but assumes that counter can not be copied or at least is much difficult to copy. I think this needs to be explained.

**Comment by thorduri** [comment]
The counter is not to prevent cloning, but to detect it, from the specifcation:

> The server can compare the counter value that the U2F device sent it and compare it against the counter value it saw in earlier interactions with the same U2F device. If the counter value has moved backward, it signals that there is more than one U2F device with the same key pair for the origin (i.e., a clone of the U2F device has been created at some point).

This is an issue mostly for U2F devices without tamper-resistant secure elements (e.g software implementations) unlike the Yubico U2F security keys.
