### ISSUE TITLE
Suggested edit for PGP/Git_signing

### ISSUE THREAD

**Issue by alerque** [Yubico/developers.yubico.com#36]
The git config value key on this line is wrong:

    $ git config --global user.signkey AABBCCDD

It should be `user.signingkey`. 

The git-config man page confirms:

        user.signingKey
           If git-tag(1) or git-commit(1) is not selecting the key you want it to automatically
           when creating a signed tag or commit, you can override the default selection
           with this variable. This option is passed unchanged to gpg’s --local-user
           parameter, so you may specify a key using any method that gpg supports.

**Comment by jonathancross** [comment]
Thanks for this fix! I've been wondering how it was that I had that error in my git config and just traced it back to this page...  Cheers.
