### ISSUE TITLE
Document YubiHSM2's FIPS mode

### ISSUE THREAD

**Issue by joernheissler** [Yubico/developers.yubico.com#377]
Hello,
how does the FIPS version of the YubiHSM2 differ from the "normal" version?
Only difference that I found so far is that it got a FIPS mode which can be enabled through an undocumented option. But what does that mode actually do?

Cheers

**Comment by HRio** [comment]
The fips option was added in https://github.com/Yubico/yubihsm-shell/commit/2d84b84855b88264067321b2a1ff418e3a4a6212 but as stated in this ticket there is no documentation.

Is it enabled with `01` and the default is `00`? are there any other valid settings? Also why is the value `00` for a YubiHSM 2 FIPS?

**Comment by HRio** [comment]
From "FIPS 140-2 Security Policy v1.3" for "YubiHSM 2 Cryptographic Module"
```
3. Secure Operation
The module supports both an Approved mode and non-Approved mode of operation, which
can be configured per the instructions in this Security Policy.

3.1 Installation
There are no specific instructions for the installation of the YubiHSM2 Cryptographic Module.
The module will come installed within a YubiHSM 2 and is ready for use once plugged-into a
USB port and initialized per the instructions in Section 3.2.

3.2 Initialization
To configure the module into the Approved mode of operation, the operator shall perform the
following:
1. Use the “Set Option” service as follows: 4f000405000101 or “put option 0 fips-mode 01”
2. Import new Authentication Keys to replace the default values.
To check the mode of operation, the operator may perform the following:
1. Use the “Get Option” service as follows: “get option 0 fips-mode”
a. “01” return code indicates the Approved mode
b. “00” return code indicates the non-Approved mode
To toggle the mode of operation, the module will first verify that all CSPs have been deleted,
which can be performed via a “Reset Device” service.
```

Ref: https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3916.pdf

Question: so a user of the "YubiHSM 2 FIPS 140-2 Validatated module", must manually set an option not mentioned in the YubiHSM2 end-user documentation to be in "Approved mode of operation" for FIPS 140-2? Or how should we understand this?
