### ISSUE TITLE
Suggested edit for PGP/Importing_keys

### ISSUE THREAD

**Issue by sanmai-NL** [Yubico/developers.yubico.com#38]
> previously generate key.
> `->`
> previously generated key.

The procedure does **not** work for
- Yubikey Neo
- with a Linux 4.5.1 VM
- under Windows 10 Education
- under the current VMWare player hypervisor 12.1.1.

Please start the text by warning that users with such an environment need to [disable shared mode for smart card devices](https://pubs.vmware.com/workstation-9/index.jsp?topic=%2Fcom.vmware.ws.using.doc%2FGUID-6F6D2C78-F28C-4553-8E46-F337599174DB.html) and then perform [these steps](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1033435) to allow passthrough mode to the Yubikey.

**Comment by thorduri** [comment]
Wording fixed in #54 

We'll not be adding documentation/workarounds for specific environments, as in the long term this would be a losing game.
