### ISSUE TITLE
Feature Request | Please support DSC

### ISSUE THREAD

**Issue by prnam** [Yubico/developers.yubico.com#409]
Hey Team,
India has this mandate need of DSC for any individual or business who needs to sign docs, patent, e-tendering etc. These days they are providing something called ProxyKey, I wanted Yubi Key support and hoping I can have everything in one key i.e Yubi Key.

Link to know more about DSC: https://mca.gov.in/MinistryV2/digitalsignaturecertificate.html
Diff Signature & Encryption from CA: https://www.e-mudhra.com/Type-of-certificates.html#encryprtioncertificate
MCA DSC info: https://mca.gov.in/MinistryV2/acquiredsc.html

This may be good feature add-on for your company, that you can share with your management. But you need work with MCA to get you listed on certificate authority.

**Comment by prnam** [comment]
Duplicate of #743

**Comment by Risinggoblin** [comment]
This was marked completed. Is this supported now?

**Comment by balakrishnanpai** [comment]
Whilst from a technical standpoint, Yubikey FIPS 140-2 validated keys are compliant with the CCA specifications, the ecosystem does not support it.

For e.g Govt website interaction with CA middleware which in turn interacts with the token driver.

Whilst the introduction of CAs was intended to removes the barriers of entry by chipping away at  “babugiri“, it has only created an additional subsection of vendors and all sorts of software that would make foreigners cringe.

My solution was to create a VM on my laptop and keep all the CA related stuff in there. Especially with the demand of having to install root keys into my OS. 

Certain Ca allows you to export the certificates. You can use this only PIV slot. You can use this for offline document signing, but you can use Yubikey as an identity token
