### ISSUE TITLE
Suggested edit for PGP/Card_edit

### ISSUE THREAD

**Issue by SueHeim** [Yubico/developers.yubico.com#41]
Recommend that this paragraph:

Make sure the device is in OTP/CCID or CCID mode, use the YubiKey personalization tool "ykpersonalize -m82" to switch.

be changed as follows:

Make sure the device is in OTP/CCID/U2F or CCID mode. Use the YubiKey Personalization Tool command "ykpersonalize -m86" to change modes for YubiKey 4 and YubiKey NEO devices sold after September 2014. For devices sold prior to September 2014, use "ykpersonalize -m82". 

Note that you can also use the YubiKey NEO Manager application to change modes. All YubiKey 4 and YubiKey NEO devices are now shipped with CCID mode enabled, by default.

**Comment by thorduri** [comment]
Fixed in #51

**Comment by thorduri** [comment]
Fixed in recent PRs.
