### ISSUE TITLE
Suggested edit for PGP/Importing_keys

### ISSUE THREAD

**Issue by teridon** [Yubico/developers.yubico.com#42]
The page directs the user to run gpg-connect-agent, but neglects to mention that the Yubikey should be connected first.  It is not obvious to the new user that the yubikey openpgp module resides on the key (as opposed to some software plugin residing on the computer).

**Comment by thorduri** [comment]
Fixed in recent PRs.

**Comment by teridon** [comment]
Thank you.   However, commit c373a98 was made to Card_edit.adoc but also should have been made to Importing_keys.adoc

**Comment by thorduri** [comment]
@teridon Hah, good catch.

Fixed.
