### ISSUE TITLE
"step-by-step configuration instructions to enable SSH authentication with the YubiKey and FIDO2" link is dead

### ISSUE THREAD

**Issue by tibbe** [Yubico/developers.yubico.com#431]
The "step-by-step configuration instructions to enable SSH authentication with the YubiKey and FIDO2" link on https://developers.yubico.com/SSH/ is dead.

**Comment by nevun** [comment]
fixed in https://github.com/Yubico/developers.yubico.com/commit/850174ae2f59ed35c9125bcdb002b6e7dd86a594 but not deployed.. :shrug:

**Comment by ricandr** [comment]
The issue has been fixed.
