### ISSUE TITLE
Suggested edit for PIV/Introduction/Admin_access

### ISSUE THREAD

**Issue by cederom** [Yubico/developers.yubico.com#45]
No information on ADMIN PIN RESET ERROR.

Error changing the PIN: Conditions of use not satisfied

WHY? HOW?

**Comment by klali** [comment]
For issues with usage of the key please contact Yubico support: https://www.yubico.com/support/raise-ticket/

**Comment by cederom** [comment]
This helped me in case of blocked PIN you can reference that article:

https://developers.yubico.com/ykneo-openpgp/ResetApplet.html

But I lost all my device content and had to resupply with keys.
