### ISSUE TITLE
Suggested edit for U2F/Protocol_details/Key_generation

### ISSUE THREAD

**Issue by kikoz** [Yubico/developers.yubico.com#46]
It sounds like "However, since U2F does not specify how to store keys, we are free to come up with another solution — so we did" is not entirely true, and your solution is in conflict with the next FIDO statement "Later, when the user attempts to authenticate, the server sends the user's Key Handle back to the browser. The browser sends this Key Handle and the hash of the origin which is requesting the authentication. The U2F device ensures that it had issued this Key Handle to that particular origin hash before performing any signing operation. If there is a mismatch no signature is returned."
As your implementation does not validate that some particular Key Handle has been issued before or not.

**Comment by dainnilsson** [comment]
I'm not sure I understand what you're referring to. Can you specify more clearly which part you think is incorrect, and how?

**Comment by kikoz** [comment]
Please disregard my comment, I was misled by the diagram "Key generation scheme used by Yubico U2F devices", which contains only "AppID" as an input parameter from the Web Service to the Web Browser. Seems it is a bit too high-level.
