### ISSUE TITLE
PGP touch functionality

### ISSUE THREAD

**Issue by chillinger** [Yubico/developers.yubico.com#559]
https://developers.yubico.com/PGP/YubiKey_5.2.3_Enhancements_to_OpenPGP_3.4.html describes the functionality to require touch for PGP Operations as well as a touch cache.
It refers to the download page of the Yubikey Manager, but there is no entry enywhere to be found, to configure this in the Manager.

Could you please clarify how this is supposed to work?

**Comment by joostd** [comment]
This functionality is described in the documentation, linked to on the Download page (_YubiKey Manager (ykman) CLI & GUI Guide_).
Specifically, you can find that [here](https://docs.yubico.com/software/yubikey/tools/ykman/OpenPGP_Commands.html#ykman-openpgp-keys-set-touch-options-key-policy)

Some examples of its use:

Require touch to use the authentication key:

	$ ykman openpgp keys set-touch aut on

Require touch to use the authentication key, but cache for 15s after use:

	$ ykman openpgp keys set-touch aut cached

View current touch policy:

	$ ykman openpgp info
	OpenPGP version:            3.4
	Application version:        5.4.3
	PIN tries remaining:        3
	Reset code tries remaining: 0
	Admin PIN tries remaining:  3
	Require PIN for signature:  Once
	Touch policies:            
	  Signature key:      Off
	  Encryption key:     Off
	  Authentication key: Cached
	  Attestation key:    Off

**Comment by chillinger** [comment]
Thank you very much for the clarification!
It was unclear to me, that the CLI variant was needed
