### ISSUE TITLE
Suggested edit for U2F/Libraries/Using_a_library

### ISSUE THREAD

**Issue by sunderipranata** [Yubico/developers.yubico.com#60]
Client-side
This section assumes that you are building a web site. If this is not the case, have a look at our U2F host libraries instead. Also note that Chrome is currently the only web browser supporting U2F.

The main part of the client is to be a middle-man between the server and the U2F device.

The easiest way to use U2F in a supported browser is to use the u2f-api.js library, which exposes two functions:

u2f.register 
Register using a U2F device.

u2f.sign 
Authenticate using a U2F device.

Example snippet

<script src="https://demo.yubico.com/js/u2f-api.js"></script>
<script>
var challenge = ... 1
u2f.sign([challenge], [],
  function(deviceResponse) {
    document.getElementById('response-input').value = JSON.stringify(deviceResponse)
    document.getElementById('login-form').submit() 2
  }
);
</script>
1	From the server (e.g. this row could be dynamically generated by the server).
2	Send device response back to server.
When registering a new device u2f.register is used instead of u2f.sign. The complete U2F JavaScript API can be found here.

For a complete example, see this demo server.

Complete example code
For complete example code (both server and client) in various languages, have a look at respective U2F library's accompanied demo server.

U2F error codes
If you get an error, check out the client error codes.

---------------------------------------------
For a complete example, see this demo server.
^it is not demo server, i suggest change sentence.

The script example is old u2f API, since now the api has been updated, it's kinda confusing.

**Comment by thorduri** [comment]
> ^it is not demo server, i suggest change sentence.

The linked resource is a demo, while the server it self isn't -- So we'll keep it as is.

I'll look into updating the example.
