### ISSUE TITLE
Suggested edit for OTP/Modhex_Converter

### ISSUE THREAD

**Issue by jdub3jdub3** [Yubico/developers.yubico.com#63]
Misspelling? Should likely read: "...namely the INCONSISTENT..."

![image](https://cloud.githubusercontent.com/assets/10049571/22249126/fd6240ee-e241-11e6-9b47-2fd93cdf056f.png)

**Comment by thorduri** [comment]
That's on purpose, contrast:

inconstant: "frequently changing; variable or irregular." or "not faithful and dependable."
with
inconsistent: "not staying the same throughout." or "not compatible or in keeping with."

Keyboard layouts are consistent (e.g. US/QWERTY are the same(-ish) across all keyboards)
but the key locations are not constant (e.g. FR/AZERTY).

Thanks for the report tho!
