### ISSUE TITLE
Suggested edit for PGP/Git_signing

### ISSUE THREAD

**Issue by tobypinder** [Yubico/developers.yubico.com#64]
In the git variables section, you include

```markdown 
format.signOff 
Enables --signoff by default in format-patch;
```

This feature is completely unrelated to [GPG signing](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work) and entirely related to the `--signoff` feature that merely adds a `Signed-Off-By:` header to a commit. This should be completely removed to prevent (understandable) confusion between the "signoff" and "gpg sign" features as the former is unrelated to security.

**Comment by thorduri** [comment]
Good catch, I've dropped the reference to it.
