### ISSUE TITLE
Suggested edit for PIV/Introduction/Certificate_slots

### ISSUE THREAD

**Issue by bmomjian** [Yubico/developers.yubico.com#78]
The "only once" documented PIN requirements do not seem to match, or at least I can't figure out how they are used.  With Yubikey 4 Nano, Openssl always requires a pin for every private key slot access, while pkcs15-crypt requires a pin for every access except 9e.  When is the "only once per session" option used?  And does single session mean a single key insertion?

**Comment by klali** [comment]
The once per session generally means that when the software selects the applet again it will gain a new session. If you do execute some software that needs several signatures within one invocation it will only ask for pin once, but every time you execute that software it will re-select and need to verify again.
