### ISSUE TITLE
Suggested edit for PIV/Guides/SSH_with_PIV_and_PKCS11

### ISSUE THREAD

**Issue by tetlowgm** [Yubico/developers.yubico.com#88]
OpenSC is not needed with MacOS. I'm able to use libykcs11 directly with ssh-add:

MacOS (nothing additional needed):
`ssh-add -s /usr/local/lib/libykcs11.dylib`

Linux/FreeBSD (needs pcscd running):
`ssh-add -s /usr/local/lib/libykcs11.so`

**Comment by joostd** [comment]
Thanks, we have updated the guide to refer to libykcs instead.
