### ISSUE TITLE
Typo in https://developers.yubico.com/yubikey-personalization/ - "to build it's manpage"

### ISSUE THREAD

**Issue by shlomif** [Yubico/developers.yubico.com#91]
The "it's" should be "its".

**Comment by klali** [comment]
fixed in https://github.com/Yubico/yubikey-personalization/commit/0a5ed60ac7024cebd509dafb6c20441f60a71ab5

**Comment by shlomif** [comment]
On Sun, 10 Dec 2017 23:47:57 -0800
Klas Lindfors <notifications@github.com> wrote:

> fixed in
> https://github.com/Yubico/yubikey-personalization/commit/0a5ed60ac7024cebd509dafb6c20441f60a71ab5
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Chuck Norris/etc. Facts - http://www.shlomifish.org/humour/bits/facts/

One of Rincewind’s tutors had said of him that “to call his understanding of
magical theory abysmal is to leave no suitable word to describe his grasp of
its practice”.
    — Terry Practhett, Sourcery

Please reply to list if it's a mailing list post - http://shlom.in/reply .
