### ISSUE TITLE
Suggested edit for PIV/Guides/Device_setup

### ISSUE THREAD

**Issue by jmyreen** [Yubico/developers.yubico.com#95]
The documentation for `yubico-piv-tool` (v. 1.5.0) does not seem to match how the utility really works. The key value on the command line after `--key` is ignored when using `-a set-mgm-key` and the new value is always asked interactively. Sample session (on Linux) setting the key to its current value:

```
% yubico-piv-tool -a set-mgm-key -n $key --key $key
Enter management key: 
Successfully set new management key.
%
```
The variable `key` contains a string consisting of 48 hex characters.

**Comment by klali** [comment]
Thanks!

This is fixed with cb05c8c9b15f94bdf3422b02d707a71176e0528c the issue is that these options are optionally empty and then have to follow straight on the option (like --new-key=$key)
